# -*- coding: utf-8 -*-
"""sin_cos_deriv.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132OgxyceuAVe9-7O_DH10AauDv0K-gqc
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

# 1. Verificación Simbólica (La "Calculadora" de álgebra)
x = sp.symbols('x')
funcion = sp.sin(2*x)
derivada = sp.diff(funcion, x)

print("--- Resultado Matemático ---")
print(f"Función: {funcion}")
print(f"Derivada: {derivada}")
# Python dirá: 2*cos(2*x)

# 2. Visualización (Para ver la 'onda' y su cambio)
# Creamos números del 0 al 2*Pi
x_vals = np.linspace(0, 2*np.pi, 100)
y_vals = np.sin(2*x_vals)            # Función original
dy_vals = 2 * np.cos(2*x_vals)       # Derivada

plt.figure(figsize=(10, 5))
plt.plot(x_vals, y_vals, label='Original: sin(2x)', color='blue')
plt.plot(x_vals, dy_vals, label='Derivada: 2cos(2x)', color='red', linestyle='--')
plt.title('Visualizando el Cambio: Función vs Derivada')
plt.legend()
plt.grid(True)
plt.show()